name: ipa
on: [push]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - iOS
    steps:
      - uses: actions/checkout@v1
      - uses: maxim-lobanov/setup-cocoapods@v1
        with:
          podfile-path: ios/Podfile.lock
      - uses: mxcl/xcodebuild@v3
        with:
          action: build
          working-directory: ./ios/app
