name: ipa
on: [push]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - iOS
    steps:
      - run: ls
      - run: pwd
      - uses: mxcl/xcodebuild@v3
        with:
          working-directory: ./ios/app
