name: ipa
on: [push]
jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform:
          - iOS
    steps:
      - uses: actions/checkout@v1
      - run: |
          npm install
          ./node_modules/react-native-webrtc/tools/downloadBitcode.sh
          cd ios
          pod install
      - uses: mxcl/xcodebuild@v3
        with:
          action: build
          working-directory: ./ios/app
